### ISSUE TITLE
It can’t be found on quest

### ISSUE THREAD

**Issue by haxhaxhax526** [XavierSJC/pavlov-vr-quest-server#12] opened 2022-12-19 03:26 UTC
I was looking and I made sure my info was right but I couldn’t find the server on quest

**Comment by XavierSJC** [comment] 2022-12-28 02:48
Please give more details about your issue:

* Which command that you did do.
* Log of the Pavlov server

You can find the log file: /home/steam/pavlovserver/Pavlov/Saved/Logs/Pavlov.log
If you continue opening issues without these detail, I will block you.

**Comment by haxhaxhax526** [comment] 2022-12-28 03:39
There is no directory there it didn’t create one

**Comment by XavierSJC** [comment] 2023-01-05 04:00
I couldn't reproduce the issue with these details, closing.

**Closed as not planned by XavierSJC** 2023-01-05 04:00 UTC
Labels: question
